// Generated by CoffeeScript 1.7.1
(function() {
  var html;

  html = htmlMake(function() {
    return this.div({
      id: "a1"
    }, function() {
      return "world";
    });
  });

  window.t = html;

}).call(this);

//# sourceMappingURL=test.map
