// Generated by CoffeeScript 1.7.1
(function() {
  var HtmlMaker, helper,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  helper = require("src/helper");

  HtmlMaker = (function() {
    function HtmlMaker() {
      this.draw = __bind(this.draw, this);
      this.toString = __bind(this.toString, this);
      this.start = __bind(this.start, this);
    }

    HtmlMaker.prototype.start = function(draw) {
      var tag, _i, _len, _ref;
      this.buffer = [];
      _ref = helper.tags;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tag = _ref[_i];
        this[tag] = helper.partial(this.el, this, tag);
      }
      this.use(draw, this);
      return this;
    };

    HtmlMaker.prototype.el = function(parent, tag, attrs, func) {
      var obj, tgname, _i, _len, _ref;
      this.func = func;
      this.attrs = attrs;
      this.buffer = [];
      this.tag = tag;
      obj = {};
      _ref = helper.tags;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tgname = _ref[_i];
        obj[tgname] = helper.partial(HtmlMaker.prototype.el, this, tgname);
      }
      helper.use(this.func, obj);
      return parent.buffer.push(this);
    };

    HtmlMaker.prototype.toString = function() {
      var el;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = this.buffer;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          el = _ref[_i];
          _results.push(this.draw(el));
        }
        return _results;
      }).call(this)).join("");
    };

    HtmlMaker.prototype.draw = function(el) {
      var attrs, content, key, subEl, val, _i, _len, _ref, _ref1;
      attrs = "";
      _ref = el.attrs;
      for (key in _ref) {
        val = _ref[key];
        attrs += "" + key + "='" + val + "' ";
      }
      content = [];
      console.log(el);
      console.log(el.buffer);
      if (!el.text) {
        _ref1 = el.buffer;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          subEl = _ref1[_i];
          content.push(this.draw(subEl));
        }
      } else {
        content = [el.text];
      }
      return "<" + el.tag + " " + attrs + ">" + (content.join('')) + "</" + el.tag + ">";
    };

    return HtmlMaker;

  })();

  if (typeof module === "object" && typeof module.exports === "object") {
    module.exports = (new HtmlMaker).start;
  } else {
    if (window) {
      window.htmlMake = (new HtmlMaker).start;
      window.HtmlMaker = HtmlMaker;
    }
  }

}).call(this);

//# sourceMappingURL=html-maker.map
