// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  Helper({
    partial: function() {
      var f, values;
      f = arguments[0], values = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return f.apply(this, values.concat(args));
      };
    },
    use: function() {
      var args, context, fnc;
      fnc = arguments[0], context = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      if (fnc && typeof fnc === "function") {
        return fnc.apply(context, args);
      } else {
        return fnc;
      }
    }
  });

  module.exports = Helper;

}).call(this);

//# sourceMappingURL=helper.map
