// Generated by CoffeeScript 1.9.1
(function() {
  var Helper,
    slice = [].slice;

  Helper = {
    partial: function() {
      var bounded, element, f, values;
      f = arguments[0], values = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      bounded = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = values.length; i < len; i++) {
          element = values[i];
          results.push(element);
        }
        return results;
      })();
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return f.apply(this, bounded.concat(args));
      };
    },
    use: function() {
      var args, context, fnc;
      fnc = arguments[0], context = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
      if (fnc && typeof fnc === "function") {
        return fnc.apply(context, args);
      } else {
        return fnc;
      }
    },
    makeTagFunctions: function(obj) {
      var i, len, ref, results, tgname;
      ref = Helper.tags;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        tgname = ref[i];
        results.push(obj[tgname] = Helper.partial(obj.el, obj, tgname));
      }
      return results;
    },
    tags: ["div", "ul", "li", "form", "input", "select", "option", "i", "a", "h1", "h2", "h3", "h4", "span"]
  };

  module.exports = Helper;

}).call(this);

//# sourceMappingURL=helper.js.map
