// Generated by CoffeeScript 1.9.2
(function() {
  var HtmlMaker, helper,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  helper = require("src/helper");

  HtmlMaker = (function() {
    function HtmlMaker() {
      this.draw = bind(this.draw, this);
      this.toString = bind(this.toString, this);
      this.start = bind(this.start, this);
    }

    HtmlMaker.prototype.start = function(func, context) {
      var res, self;
      self = context || this;
      self.buffer = [];
      helper.makeTagFunctions(self);
      res = helper.use(func, self);
      helper.dropTagFunctions(self);
      return this.toString(self.buffer, res);
    };

    HtmlMaker.prototype.el = function(parent, tag, attrs, func) {
      var obj;
      obj = {};
      obj.buffer = [];
      obj.tag = tag;
      obj.el = this.el;
      obj.attrs = {};
      helper.makeTagFunctions(obj);
      if (!func && typeof attrs === "function") {
        func = attrs;
      }
      if (func) {
        if (typeof func === "function") {
          obj.text = helper.use(func, obj);
        } else {
          obj.text = func;
        }
      }
      if (attrs) {
        if (typeof attrs === "object") {
          obj.attrs = attrs;
        }
        if (!func && typeof attrs === "string") {
          obj.text = attrs;
        }
        if (func && typeof attrs === "string") {
          obj.attrs = {
            "class": attrs
          };
        }
      }
      this.buffer.push(obj);
      return void 0;
    };

    HtmlMaker.prototype.toString = function(buffer, end) {
      var el, res;
      res = ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = buffer.length; i < len; i++) {
          el = buffer[i];
          results.push(this.draw(el));
        }
        return results;
      }).call(this)).join("");
      if (end) {
        res += end;
      }
      return res;
    };

    HtmlMaker.prototype.draw = function(el) {
      var attrs, content, i, key, len, ref, subEl, val;
      attrs = (function() {
        var ref, results;
        ref = el.attrs;
        results = [];
        for (key in ref) {
          val = ref[key];
          results.push([key + "='" + val + "'"]);
        }
        return results;
      })();
      content = [];
      ref = el.buffer;
      for (i = 0, len = ref.length; i < len; i++) {
        subEl = ref[i];
        content.push(this.draw(subEl));
      }
      if (el.text) {
        content.push(el.text);
      }
      return "<" + el.tag + (attrs.length > 0 ? " " + attrs.join(" ") : "") + ">" + (content.join('')) + "</" + el.tag + ">";
    };

    return HtmlMaker;

  })();

  if (typeof module === "object" && typeof module.exports === "object") {
    module.exports = (new HtmlMaker).start;
  }

  try {
    window.htmlmake = (new HtmlMaker).start;
  } catch (_error) {}

}).call(this);

//# sourceMappingURL=html-maker.js.map
